In [1]:
print('surbhi')

surbhi


In [2]:
print('helo i am from nagpur')

helo i am from nagpur


In [3]:
A = 30

In [4]:
type(A)

int

In [5]:
B = 4.5

In [6]:
type(B)

float

In [7]:
C = 'surbhi'

In [8]:
type(C)

str

In [9]:
type(C)

str

In [10]:
print(A)

30


In [11]:
print(C)

surbhi


In [12]:
C

'surbhi'

In [13]:
sur = [15,5,6,8,78,67,95]

In [14]:
sur

[15, 5, 6, 8, 78, 67, 95]

In [15]:
len(sur)

7

In [16]:
sur[3]

8

In [17]:
sur[5]

67

In [19]:
sur[2:5]

[6, 8, 78]

In [20]:
sur[3:]

[8, 78, 67, 95]

In [21]:
sur

[15, 5, 6, 8, 78, 67, 95]

In [22]:
sur[:4]

[15, 5, 6, 8]

In [23]:
# list is mutalbe

In [24]:
sur

[15, 5, 6, 8, 78, 67, 95]

In [25]:
sur[3] = 'surbhi'

In [26]:
sur

[15, 5, 6, 'surbhi', 78, 67, 95]

In [27]:
sur.append(56)

In [28]:
sur

[15, 5, 6, 'surbhi', 78, 67, 95, 56]

In [29]:
sur.append('dany')

In [30]:
sur

[15, 5, 6, 'surbhi', 78, 67, 95, 56, 'dany']

In [31]:
# 21 april

In [33]:
i = 1
while i<5:
    print(i)
    i=i+1


1
2
3
4


In [35]:
# list comprenhensive (we can create list in run time using for loop)

In [36]:
x = [1,2,3,4,5]

In [37]:
aarti = []

In [38]:
aarti

[]

In [39]:
for i in x:
    aarti.append(i**2)

In [40]:
aarti

[1, 4, 9, 16, 25]

In [41]:
surbhi = [i**2 for i in x]

In [42]:
surbhi

[1, 4, 9, 16, 25]

In [43]:
sur1 = [i**3 for i in x]

In [44]:
sur1

[1, 8, 27, 64, 125]

In [45]:
dany = [i**2 for i in x]

In [46]:
dany

[1, 4, 9, 16, 25]

In [47]:
# UDF

In [48]:
def arti(a,b):
    c = a + b
    return c

In [49]:
type(arti)

function

In [50]:
arti(10,20)

30

In [51]:
def time2(a):
    return a**2

In [52]:
time2(2)

4

In [53]:
time2(5)

25

In [54]:
def cube(a):
    return a**3

In [55]:
cube(3)

27

In [56]:
import numpy as np

In [57]:
lst = [48,59,66,3,2,89]

In [58]:
type(lst)

list

In [59]:
arr = np.array(lst)

In [60]:
type(arr)

numpy.ndarray

In [61]:
arr1 = np.array([12,5,6,8,9])

In [62]:
arr1

array([12,  5,  6,  8,  9])

In [63]:
arr

array([48, 59, 66,  3,  2, 89])

In [64]:
arr.shape

(6,)

In [65]:
arr1.shape

(5,)

In [66]:
arr2 = np.array([[3,4,5],[5,6,8]])

In [67]:
arr2

array([[3, 4, 5],
       [5, 6, 8]])

In [68]:
arr2.shape

(2, 3)

In [69]:
#(row,col)