In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5,6,8]

In [3]:
arr = np.array(lst)

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 8])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(7,)

In [7]:
arr1 = np.array([58,56,8,9,7])

In [8]:
arr1

array([58, 56,  8,  9,  7])

In [9]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
arr2 = np.array(lst1)

In [11]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr2.shape

(3, 3)

In [13]:
arr3 = np.array([[2,3],[4,5],[5,6],[7,8]])

In [14]:
arr3

array([[2, 3],
       [4, 5],
       [5, 6],
       [7, 8]])

In [15]:
arr3.shape

(4, 2)

In [16]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(20,40)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [25]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [26]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [27]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [28]:
np.linspace(1,5,2)

array([1., 5.])

In [29]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [30]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [31]:
np.random.rand(5)

array([0.43325721, 0.43282533, 0.59080279, 0.20413014, 0.78338728])

In [32]:
np.random.randint(1,100,20)

array([64, 11, 74, 52, 13, 23, 78, 21, 60, 86, 41, 50, 46, 30, 74, 87, 67,
       67, 40, 76])

In [33]:
arr = np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.shape

(25,)

In [36]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr1 = np.arange(20)

In [39]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
arr1.shape

(20,)

In [42]:
arr1.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [43]:
arr1.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [44]:
arr1.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [45]:
arr1.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
arr1.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [49]:
arr3 = np.array([34,6,2,78,345,789,34,5,65,784,3,42])

In [50]:
arr3

array([ 34,   6,   2,  78, 345, 789,  34,   5,  65, 784,   3,  42])

In [52]:
arr3.max()

789

In [53]:
arr3.min()

2

In [54]:
arr3.argmax()

5

In [55]:
arr3.argmin()

2

In [56]:
arr3

array([ 34,   6,   2,  78, 345, 789,  34,   5,  65, 784,   3,  42])

In [57]:
arr3[3]

78

In [59]:
arr3[7]

5

In [60]:
arr3[1:6]

array([  6,   2,  78, 345, 789])

In [61]:
arr3[:5]

array([ 34,   6,   2,  78, 345])

In [62]:
arr3[5:]

array([789,  34,   5,  65, 784,   3,  42])

In [63]:
arr3[5] = 1000

In [64]:
arr3

array([  34,    6,    2,   78,  345, 1000,   34,    5,   65,  784,    3,
         42])

In [66]:
arr3[1:6] = 2000

In [67]:
arr3

array([  34, 2000, 2000, 2000, 2000, 2000,   34,    5,   65,  784,    3,
         42])

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
arr.shape

(25,)

In [70]:
arr.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [71]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])